name: run tests
on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: say hello
        run: echo 'hello from pipeline'
  test-utls:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout and clone repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name:
        run: npm run test-utils
  test-app:
    needs: test-utils
    runs-on: ubuntu-latest 
    steps:
      - name: checkout and clone repo     
        uses: actions/checkout@v4
      - name: setup-psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: my_db
          postgresql password: password
          postgresql user: userface
      - name: install dependencies
        run: npm install
      - name: run tests
        run: PGDATABASE=my_db PGPASSWORD=password PGUSER=userface npm run test-app



