name: tests
on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
     - name: say hello
       run: echo 'hello from pipeline'
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: check out and clone repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: run utils test
        run: npm run test-utils
  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: check out and clone repo
        uses: actions/checkout@v4
      - name: setup psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: my_database
          postgresql user: mrsTesterson
          postgresql password: verysecurepassword
      - name: install dependencies
        run: npm install
      - name: run tests
        run: PGPASSWORD=verysecurepassword PGDATABASE=my_database PGUSER=mrsTesterson npm run test-app
